import { siteConfig } from '@/lib/site'

export type ToolType = 'static' | 'api' | 'ai' | 'reference'

export interface ToolFaq {
  question: string
  answer: string
}

export interface ToolDefinition {
  id: string
  title: string
  description: string
  longDescription?: string
  category: string
  icon: string
  keywords: string[]
  type: ToolType
  addedAt: string
  relatedTools?: string[]
  faq?: ToolFaq[]
  component: () => Promise<{ default: React.ComponentType }>
}

export interface CategoryDefinition {
  id: string
  name: string
  description: string
  icon: string
}

const defaultFaq: ToolFaq[] = [
  {
    question: 'Is this tool free?',
    answer: `Yes. Every ${siteConfig.name} utility is free with no sign-up, usage limits, or paywalls.`,
  },
  {
    question: 'Do you store my data?',
    answer: 'No. Processing happens entirely in your browser. Your input never leaves your device.',
  },
  {
    question: 'Can I use this tool offline?',
    answer: 'Yes. Once the page loads, most tools continue working without an internet connection.',
  },
]

export const categories: CategoryDefinition[] = [
  {
    id: 'text',
    name: 'Text Tools',
    description: 'Format, analyze, and transform text directly in your browser.',
    icon: 'type',
  },
  {
    id: 'encoding',
    name: 'Converters',
    description: 'Encode and decode Base64, URLs, and other common data formats.',
    icon: 'arrow-left-right',
  },
  {
    id: 'generators',
    name: 'Generators',
    description: 'Create UUIDs, passwords, and other random values instantly.',
    icon: 'sparkles',
  },
  {
    id: 'calculators',
    name: 'Calculators',
    description: 'Quick calculators for finance, dates, and everyday math.',
    icon: 'calculator',
  },
  {
    id: 'developer',
    name: 'Developer',
    description: 'Debug tokens, test regex patterns, and inspect developer data formats.',
    icon: 'code-2',
  },
  {
    id: 'security',
    name: 'Security',
    description: 'Generate cryptographic hashes and inspect security-related data.',
    icon: 'shield',
  },
  {
    id: 'math',
    name: 'Math',
    description: 'Percentage, ratio, and everyday math calculators.',
    icon: 'percent',
  },
  {
    id: 'datetime',
    name: 'Date & Time',
    description: 'Convert timestamps, timezones, and date values instantly.',
    icon: 'clock',
  },
  {
    id: 'network',
    name: 'Network',
    description: 'CIDR calculators, HTTP references, and networking utilities.',
    icon: 'network',
  },
]

export const tools: Record<string, ToolDefinition> = {
  'json-formatter': {
    id: 'json-formatter',
    title: 'JSON Formatter',
    description: 'Format, validate, and minify JSON instantly',
    longDescription:
      'Free online JSON formatter and validator. Pretty-print JSON with syntax-aware indentation, minify for production, or validate structure before deployment.',
    category: 'text',
    icon: 'braces',
    keywords: ['json', 'format', 'validate', 'pretty print', 'minify', 'beautify'],
    type: 'static',
    addedAt: '2026-01-15',
    relatedTools: ['base64-encoder', 'url-encoder', 'word-counter'],
    faq: [
      {
        question: 'How do I format JSON online?',
        answer: 'Paste your JSON into the input box and click Format. The tool validates syntax and applies readable indentation automatically.',
      },
      {
        question: 'Can this tool minify JSON?',
        answer: 'Yes. Switch to Minify mode to remove whitespace and produce compact JSON for APIs and production use.',
      },
      ...defaultFaq,
    ],
    component: () =>
      import('@/components/tools/json-formatter').then((mod) => ({ default: mod.JsonFormatter })),
  },
  'base64-encoder': {
    id: 'base64-encoder',
    title: 'Base64 Encoder',
    description: 'Encode plain text to Base64',
    longDescription:
      'Convert text strings to Base64 encoding online. Useful for APIs, data URIs, and embedding binary data in JSON or XML.',
    category: 'encoding',
    icon: 'binary',
    keywords: ['base64', 'encode', 'text', 'converter'],
    type: 'static',
    addedAt: '2026-01-18',
    relatedTools: ['base64-decoder', 'url-encoder', 'json-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/base64-encoder').then((mod) => ({ default: mod.Base64Encoder })),
  },
  'base64-decoder': {
    id: 'base64-decoder',
    title: 'Base64 Decoder',
    description: 'Decode Base64 back to plain text',
    longDescription:
      'Decode Base64 strings to readable text. Handles standard Base64 input and shows clear errors for invalid payloads.',
    category: 'encoding',
    icon: 'binary',
    keywords: ['base64', 'decode', 'text', 'converter'],
    type: 'static',
    addedAt: '2026-01-18',
    relatedTools: ['base64-encoder', 'url-decoder', 'json-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/base64-decoder').then((mod) => ({ default: mod.Base64Decoder })),
  },
  'url-encoder': {
    id: 'url-encoder',
    title: 'URL Encoder',
    description: 'Percent-encode strings for safe URLs',
    longDescription:
      'Encode special characters for use in URLs and query strings. Supports component encoding for paths, params, and form values.',
    category: 'encoding',
    icon: 'link',
    keywords: ['url', 'encode', 'percent encoding', 'uri'],
    type: 'static',
    addedAt: '2026-01-20',
    relatedTools: ['url-decoder', 'base64-encoder', 'json-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/url-encoder').then((mod) => ({ default: mod.UrlEncoder })),
  },
  'url-decoder': {
    id: 'url-decoder',
    title: 'URL Decoder',
    description: 'Decode percent-encoded URL strings',
    longDescription:
      'Convert percent-encoded URLs back to readable text. Helpful when debugging redirects, query parameters, and encoded paths.',
    category: 'encoding',
    icon: 'link-2',
    keywords: ['url', 'decode', 'percent encoding', 'uri'],
    type: 'static',
    addedAt: '2026-01-20',
    relatedTools: ['url-encoder', 'base64-decoder', 'json-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/url-decoder').then((mod) => ({ default: mod.UrlDecoder })),
  },
  'uuid-generator': {
    id: 'uuid-generator',
    title: 'UUID Generator',
    description: 'Generate RFC 4122 UUID v4 identifiers',
    longDescription:
      'Create cryptographically random UUID v4 values for databases, APIs, and distributed systems. Copy single or bulk UUIDs in one click.',
    category: 'generators',
    icon: 'fingerprint',
    keywords: ['uuid', 'guid', 'generate', 'unique identifier', 'v4'],
    type: 'static',
    addedAt: '2026-01-22',
    relatedTools: ['password-generator', 'json-formatter', 'base64-encoder'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/uuid-generator').then((mod) => ({ default: mod.UuidGenerator })),
  },
  'password-generator': {
    id: 'password-generator',
    title: 'Password Generator',
    description: 'Create strong, customizable passwords',
    longDescription:
      'Generate secure random passwords with configurable length and character sets. All generation happens locally in your browser.',
    category: 'generators',
    icon: 'key-round',
    keywords: ['password', 'generate', 'secure', 'random', 'strong password'],
    type: 'static',
    addedAt: '2026-01-22',
    relatedTools: ['uuid-generator', 'base64-encoder', 'json-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/password-generator').then((mod) => ({
        default: mod.PasswordGenerator,
      })),
  },
  'word-counter': {
    id: 'word-counter',
    title: 'Word Counter',
    description: 'Count words, characters, sentences, and lines',
    longDescription:
      'Analyze text with live word, character, sentence, and line counts. Ideal for essays, social posts, SEO copy, and content limits.',
    category: 'text',
    icon: 'type',
    keywords: ['word count', 'character count', 'text analysis', 'line count'],
    type: 'static',
    addedAt: '2026-01-25',
    relatedTools: ['json-formatter', 'url-encoder', 'password-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/word-counter').then((mod) => ({ default: mod.WordCounter })),
  },
  'age-calculator': {
    id: 'age-calculator',
    title: 'Age Calculator',
    description: 'Calculate exact age from a birthdate',
    longDescription:
      'Find your precise age in years, months, and days from any birthdate. Includes next birthday countdown and zodiac sign.',
    category: 'calculators',
    icon: 'cake',
    keywords: ['age calculator', 'birthdate', 'how old am i', 'date'],
    type: 'static',
    addedAt: '2026-02-01',
    relatedTools: ['emi-calculator', 'word-counter', 'uuid-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/age-calculator').then((mod) => ({ default: mod.AgeCalculator })),
  },
  'emi-calculator': {
    id: 'emi-calculator',
    title: 'EMI Calculator',
    description: 'Calculate loan EMI, interest, and total payable',
    longDescription:
      'Compute monthly EMI for home, car, and personal loans. Adjust principal, interest rate, and tenure to compare repayment scenarios.',
    category: 'calculators',
    icon: 'calculator',
    keywords: ['emi calculator', 'loan', 'interest', 'finance', 'mortgage'],
    type: 'static',
    addedAt: '2026-02-05',
    relatedTools: ['age-calculator', 'word-counter', 'password-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/emi-calculator').then((mod) => ({ default: mod.EmiCalculator })),
  },
  'hash-generator': {
    id: 'hash-generator',
    title: 'Hash Generator',
    description: 'Generate SHA-256, SHA-384, and SHA-512 hashes',
    longDescription:
      'Compute cryptographic hashes from any text using SHA-256, SHA-384, or SHA-512. All hashing runs locally via the Web Crypto API — your input never leaves the browser.',
    category: 'security',
    icon: 'shield-check',
    keywords: ['hash generator', 'sha256', 'sha512', 'checksum', 'cryptographic hash'],
    type: 'static',
    addedAt: '2026-02-10',
    relatedTools: ['base64-encoder', 'jwt-decoder', 'password-generator'],
    faq: [
      {
        question: 'What hash algorithms are supported?',
        answer: 'SHA-256, SHA-384, and SHA-512 via the browser Web Crypto API. MD5 is not included because it is cryptographically broken.',
      },
      ...defaultFaq,
    ],
    component: () =>
      import('@/components/tools/hash-generator').then((mod) => ({ default: mod.HashGenerator })),
  },
  'case-converter': {
    id: 'case-converter',
    title: 'Case Converter',
    description: 'Convert text to uppercase, lowercase, title, snake, and camel case',
    longDescription:
      'Transform text between common casing formats: UPPERCASE, lowercase, Title Case, snake_case, and camelCase. Ideal for variable naming, headings, and data cleanup.',
    category: 'text',
    icon: 'case-sensitive',
    keywords: ['case converter', 'uppercase', 'lowercase', 'camelcase', 'snake case', 'title case'],
    type: 'static',
    addedAt: '2026-02-10',
    relatedTools: ['word-counter', 'json-formatter', 'html-encoder'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/case-converter').then((mod) => ({ default: mod.CaseConverter })),
  },
  'jwt-decoder': {
    id: 'jwt-decoder',
    title: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Token headers and payloads',
    longDescription:
      'Paste a JWT to decode its header and payload JSON instantly. Useful for debugging authentication tokens, inspecting claims, and verifying token structure.',
    category: 'developer',
    icon: 'key',
    keywords: ['jwt decoder', 'json web token', 'decode jwt', 'jwt payload', 'auth token'],
    type: 'static',
    addedAt: '2026-02-11',
    relatedTools: ['json-formatter', 'hash-generator', 'base64-decoder'],
    faq: [
      {
        question: 'Does this tool verify JWT signatures?',
        answer: 'No. This decoder only parses and displays the header and payload. Signature verification requires the secret key and is not performed here.',
      },
      ...defaultFaq,
    ],
    component: () =>
      import('@/components/tools/jwt-decoder').then((mod) => ({ default: mod.JwtDecoder })),
  },
  'unix-timestamp-converter': {
    id: 'unix-timestamp-converter',
    title: 'Unix Timestamp Converter',
    description: 'Convert Unix timestamps to dates and vice versa',
    longDescription:
      'Convert between Unix epoch timestamps (seconds and milliseconds) and human-readable dates. Supports current time, custom timestamps, and ISO 8601 output.',
    category: 'datetime',
    icon: 'clock',
    keywords: ['unix timestamp', 'epoch converter', 'timestamp to date', 'date to timestamp'],
    type: 'static',
    addedAt: '2026-02-11',
    relatedTools: ['age-calculator', 'json-formatter', 'uuid-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/unix-timestamp-converter').then((mod) => ({
        default: mod.UnixTimestampConverter,
      })),
  },
  'percentage-calculator': {
    id: 'percentage-calculator',
    title: 'Percentage Calculator',
    description: 'Calculate percentages, increases, decreases, and ratios',
    longDescription:
      'Find what percentage one number is of another, calculate percentage increase or decrease, and solve everyday percentage problems instantly.',
    category: 'math',
    icon: 'percent',
    keywords: ['percentage calculator', 'percent increase', 'percent of', 'ratio calculator'],
    type: 'static',
    addedAt: '2026-02-12',
    relatedTools: ['emi-calculator', 'age-calculator', 'random-number-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/percentage-calculator').then((mod) => ({
        default: mod.PercentageCalculator,
      })),
  },
  'html-encoder': {
    id: 'html-encoder',
    title: 'HTML Encoder',
    description: 'Encode special characters to HTML entities',
    longDescription:
      'Convert characters like <, >, &, and quotes to HTML entities for safe display in web pages and prevention of XSS in templates.',
    category: 'encoding',
    icon: 'code',
    keywords: ['html encoder', 'html entities', 'escape html', 'html encode'],
    type: 'static',
    addedAt: '2026-02-12',
    relatedTools: ['url-encoder', 'base64-encoder', 'json-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/html-encoder').then((mod) => ({ default: mod.HtmlEncoder })),
  },
  'hex-encoder': {
    id: 'hex-encoder',
    title: 'Hex Encoder',
    description: 'Convert text to hexadecimal and hex back to text',
    longDescription:
      'Encode plain text to hexadecimal representation or decode hex strings back to readable text. Useful for debugging binary data and color values.',
    category: 'encoding',
    icon: 'hash',
    keywords: ['hex encoder', 'hexadecimal', 'text to hex', 'hex decode'],
    type: 'static',
    addedAt: '2026-02-13',
    relatedTools: ['base64-encoder', 'hash-generator', 'url-encoder'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/hex-encoder').then((mod) => ({ default: mod.HexEncoder })),
  },
  'lorem-ipsum-generator': {
    id: 'lorem-ipsum-generator',
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder paragraphs, sentences, and words',
    longDescription:
      'Create Lorem Ipsum placeholder text for mockups, design comps, and layout testing. Choose paragraphs, sentences, or words with one click.',
    category: 'generators',
    icon: 'file-text',
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text generator', 'lipsum'],
    type: 'static',
    addedAt: '2026-02-13',
    relatedTools: ['word-counter', 'case-converter', 'password-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/lorem-ipsum-generator').then((mod) => ({
        default: mod.LoremIpsumGenerator,
      })),
  },
  'random-number-generator': {
    id: 'random-number-generator',
    title: 'Random Number Generator',
    description: 'Generate random numbers within any range',
    longDescription:
      'Pick random integers between a minimum and maximum value. Generate single numbers or bulk lists for raffles, testing, and simulations.',
    category: 'generators',
    icon: 'dice-5',
    keywords: ['random number', 'number generator', 'random integer', 'pick a number'],
    type: 'static',
    addedAt: '2026-02-14',
    relatedTools: ['uuid-generator', 'password-generator', 'percentage-calculator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/random-number-generator').then((mod) => ({
        default: mod.RandomNumberGenerator,
      })),
  },
  'regex-tester': {
    id: 'regex-tester',
    title: 'Regex Tester',
    description: 'Test regular expressions with live match highlighting',
    longDescription:
      'Test JavaScript regular expressions against sample text with live results. Supports flags (global, case-insensitive, multiline, dotall) and shows all matches.',
    category: 'developer',
    icon: 'regex',
    keywords: ['regex tester', 'regular expression', 'regex match', 'pattern tester'],
    type: 'static',
    addedAt: '2026-02-14',
    relatedTools: ['json-formatter', 'case-converter', 'word-counter'],
    faq: [
      {
        question: 'Which regex flavor is used?',
        answer: 'JavaScript regular expressions (ECMAScript). Syntax matches what you use in Node.js and browser JavaScript.',
      },
      ...defaultFaq,
    ],
    component: () =>
      import('@/components/tools/regex-tester').then((mod) => ({ default: mod.RegexTester })),
  },
  'tip-calculator': {
    id: 'tip-calculator',
    title: 'Tip Calculator',
    description: 'Calculate tip amount and split bills between people',
    longDescription:
      'Quickly calculate tip amounts, total bill, and per-person share. Adjust tip percentage and split between any number of people.',
    category: 'calculators',
    icon: 'receipt',
    keywords: ['tip calculator', 'gratuity', 'split bill', 'restaurant tip'],
    type: 'static',
    addedAt: '2026-02-15',
    relatedTools: ['percentage-calculator', 'emi-calculator', 'bmi-calculator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/tip-calculator').then((mod) => ({ default: mod.TipCalculator })),
  },
  'bmi-calculator': {
    id: 'bmi-calculator',
    title: 'BMI Calculator',
    description: 'Calculate Body Mass Index from height and weight',
    longDescription:
      'Compute your BMI using metric (kg/cm) or imperial (lbs/inches) units. Includes weight category classification based on WHO standards.',
    category: 'calculators',
    icon: 'activity',
    keywords: ['bmi calculator', 'body mass index', 'weight calculator', 'health'],
    type: 'static',
    addedAt: '2026-02-15',
    relatedTools: ['tip-calculator', 'percentage-calculator', 'age-calculator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/bmi-calculator').then((mod) => ({ default: mod.BmiCalculator })),
  },
  'color-converter': {
    id: 'color-converter',
    title: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL',
    longDescription:
      'Convert hex color codes to RGB and HSL values with a live color preview. Essential for web design, CSS, and UI development.',
    category: 'encoding',
    icon: 'palette',
    keywords: ['color converter', 'hex to rgb', 'rgb to hsl', 'color picker'],
    type: 'static',
    addedAt: '2026-02-16',
    relatedTools: ['html-encoder', 'hex-encoder', 'json-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/color-converter').then((mod) => ({ default: mod.ColorConverter })),
  },
  'cron-parser': {
    id: 'cron-parser',
    title: 'Cron Expression Parser',
    description: 'Decode cron schedules into plain English',
    longDescription:
      'Parse standard 5-field cron expressions and understand when jobs will run. Debug cron schedules for Linux, Kubernetes, and CI pipelines.',
    category: 'developer',
    icon: 'clock',
    keywords: ['cron parser', 'cron expression', 'crontab', 'schedule parser'],
    type: 'static',
    addedAt: '2026-02-16',
    relatedTools: ['unix-timestamp-converter', 'regex-tester', 'json-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/cron-parser').then((mod) => ({ default: mod.CronParser })),
  },
  'sql-formatter': {
    id: 'sql-formatter',
    title: 'SQL Formatter',
    description: 'Format and beautify SQL queries',
    longDescription:
      'Clean up SQL queries with proper keyword casing and line breaks. Makes complex SELECT, JOIN, and INSERT statements readable for review and debugging.',
    category: 'developer',
    icon: 'database',
    keywords: ['sql formatter', 'format sql', 'sql beautifier', 'pretty print sql'],
    type: 'static',
    addedAt: '2026-02-17',
    relatedTools: ['json-formatter', 'regex-tester', 'cron-parser'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/sql-formatter').then((mod) => ({ default: mod.SqlFormatter })),
  },
  'markdown-to-html': {
    id: 'markdown-to-html',
    title: 'Markdown to HTML',
    description: 'Convert Markdown syntax to HTML instantly',
    longDescription:
      'Transform Markdown text into HTML with support for headings, bold, italic, links, lists, and inline code. Includes live HTML preview.',
    category: 'text',
    icon: 'file-code',
    keywords: ['markdown to html', 'md converter', 'markdown converter', 'html generator'],
    type: 'static',
    addedAt: '2026-02-17',
    relatedTools: ['html-encoder', 'strip-html-tags', 'word-counter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/markdown-to-html').then((mod) => ({ default: mod.MarkdownToHtml })),
  },
  'remove-line-breaks': {
    id: 'remove-line-breaks',
    title: 'Remove Line Breaks',
    description: 'Remove or replace line breaks in text',
    longDescription:
      'Clean up text copied from PDFs, emails, or documents by removing unwanted line breaks. Replace with spaces or join lines entirely.',
    category: 'text',
    icon: 'wrap-text',
    keywords: ['remove line breaks', 'delete newlines', 'text cleaner', 'join lines'],
    type: 'static',
    addedAt: '2026-02-18',
    relatedTools: ['word-counter', 'case-converter', 'strip-html-tags'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/remove-line-breaks').then((mod) => ({
        default: mod.RemoveLineBreaks,
      })),
  },
  'text-diff': {
    id: 'text-diff',
    title: 'Text Diff',
    description: 'Compare two texts and highlight differences',
    longDescription:
      'Side-by-side text comparison with added and removed line highlighting. Useful for comparing document versions, config changes, and code snippets.',
    category: 'text',
    icon: 'git-compare',
    keywords: ['text diff', 'compare text', 'diff checker', 'text comparison'],
    type: 'static',
    addedAt: '2026-02-18',
    relatedTools: ['word-counter', 'json-formatter', 'remove-line-breaks'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/text-diff').then((mod) => ({ default: mod.TextDiff })),
  },
  'slug-generator': {
    id: 'slug-generator',
    title: 'Slug Generator',
    description: 'Convert titles to URL-friendly slugs',
    longDescription:
      'Generate clean, SEO-friendly URL slugs from any title or text. Removes special characters, converts spaces to hyphens, and lowercases automatically.',
    category: 'text',
    icon: 'link',
    keywords: ['slug generator', 'url slug', 'seo slug', 'permalink generator'],
    type: 'static',
    addedAt: '2026-02-19',
    relatedTools: ['case-converter', 'word-counter', 'url-encoder'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/slug-generator').then((mod) => ({ default: mod.SlugGenerator })),
  },
  'compound-interest-calculator': {
    id: 'compound-interest-calculator',
    title: 'Compound Interest Calculator',
    description: 'Calculate compound interest and final investment value',
    longDescription:
      'Compute how much your investment grows with compound interest. Adjust principal, annual rate, compounding frequency, and time period.',
    category: 'calculators',
    icon: 'trending-up',
    keywords: ['compound interest', 'investment calculator', 'interest calculator', 'savings'],
    type: 'static',
    addedAt: '2026-02-19',
    relatedTools: ['emi-calculator', 'percentage-calculator', 'tip-calculator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/compound-interest-calculator').then((mod) => ({
        default: mod.CompoundInterestCalculator,
      })),
  },
  'line-sorter': {
    id: 'line-sorter',
    title: 'Line Sorter',
    description: 'Sort, reverse, or shuffle lines of text',
    longDescription:
      'Alphabetically sort lines A–Z or Z–A, reverse order, or randomly shuffle. Handy for lists, names, keywords, and data cleanup.',
    category: 'text',
    icon: 'arrow-down-narrow-wide',
    keywords: ['sort lines', 'alphabetical sort', 'line sorter', 'shuffle lines'],
    type: 'static',
    addedAt: '2026-02-20',
    relatedTools: ['remove-line-breaks', 'word-counter', 'case-converter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/line-sorter').then((mod) => ({ default: mod.LineSorter })),
  },
  'strip-html-tags': {
    id: 'strip-html-tags',
    title: 'Strip HTML Tags',
    description: 'Extract plain text from HTML',
    longDescription:
      'Remove all HTML tags and extract clean plain text. Useful for cleaning scraped content, email HTML, and rich text paste.',
    category: 'text',
    icon: 'eraser',
    keywords: ['strip html', 'remove html tags', 'html to text', 'extract text'],
    type: 'static',
    addedAt: '2026-02-20',
    relatedTools: ['html-encoder', 'markdown-to-html', 'word-counter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/strip-html-tags').then((mod) => ({
        default: mod.StripHtmlTags,
      })),
  },
  'sip-calculator': {
    id: 'sip-calculator',
    title: 'SIP Calculator',
    description: 'Calculate SIP maturity value and estimated returns',
    longDescription:
      'Compute Systematic Investment Plan returns for mutual funds. Enter monthly investment, expected rate, and duration to see total invested, returns, and maturity value.',
    category: 'calculators',
    icon: 'chart-line',
    keywords: ['sip calculator', 'mutual fund sip', 'sip returns', 'investment calculator india'],
    type: 'static',
    addedAt: '2026-02-21',
    relatedTools: ['emi-calculator', 'compound-interest-calculator', 'gst-calculator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/sip-calculator').then((mod) => ({ default: mod.SipCalculator })),
  },
  'gst-calculator': {
    id: 'gst-calculator',
    title: 'GST Calculator',
    description: 'Calculate GST amount for inclusive or exclusive prices',
    longDescription:
      'Calculate Goods and Services Tax at 5%, 12%, 18%, or 28% rates. Works for both GST-exclusive (add tax) and GST-inclusive (extract tax) amounts.',
    category: 'calculators',
    icon: 'indian-rupee',
    keywords: ['gst calculator', 'gst inclusive', 'gst exclusive', 'india gst'],
    type: 'static',
    addedAt: '2026-02-21',
    relatedTools: ['sip-calculator', 'emi-calculator', 'percentage-calculator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/gst-calculator').then((mod) => ({ default: mod.GstCalculator })),
  },
  'timezone-converter': {
    id: 'timezone-converter',
    title: 'Timezone Converter',
    description: 'Convert date and time between world timezones',
    longDescription:
      'Convert any date and time between major world timezones including UTC, US, Europe, and Asia. Uses the browser Intl API for accurate daylight saving handling.',
    category: 'datetime',
    icon: 'globe',
    keywords: ['timezone converter', 'time zone', 'utc converter', 'world clock'],
    type: 'static',
    addedAt: '2026-02-22',
    relatedTools: ['unix-timestamp-converter', 'date-difference-calculator', 'cron-parser'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/timezone-converter').then((mod) => ({
        default: mod.TimezoneConverter,
      })),
  },
  'date-difference-calculator': {
    id: 'date-difference-calculator',
    title: 'Date Difference Calculator',
    description: 'Calculate days, hours, and minutes between two dates',
    longDescription:
      'Find the exact difference between any two dates in days, hours, and minutes. Useful for project timelines, event countdowns, and age calculations.',
    category: 'datetime',
    icon: 'calendar-range',
    keywords: ['date difference', 'days between dates', 'date calculator', 'time between dates'],
    type: 'static',
    addedAt: '2026-02-22',
    relatedTools: ['age-calculator', 'timezone-converter', 'unix-timestamp-converter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/date-difference-calculator').then((mod) => ({
        default: mod.DateDifferenceCalculator,
      })),
  },
  'csv-to-json': {
    id: 'csv-to-json',
    title: 'CSV to JSON',
    description: 'Convert CSV data to JSON format',
    longDescription:
      'Transform comma-separated values into a JSON array of objects. Paste CSV with a header row and get clean, formatted JSON output instantly.',
    category: 'developer',
    icon: 'table',
    keywords: ['csv to json', 'convert csv', 'csv json converter', 'csv parser'],
    type: 'static',
    addedAt: '2026-02-23',
    relatedTools: ['json-to-csv', 'json-formatter', 'sql-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/csv-to-json').then((mod) => ({ default: mod.CsvToJson })),
  },
  'json-to-csv': {
    id: 'json-to-csv',
    title: 'JSON to CSV',
    description: 'Convert JSON arrays to CSV format',
    longDescription:
      'Export JSON array data to CSV for spreadsheets and databases. Automatically generates headers from object keys and handles comma escaping.',
    category: 'developer',
    icon: 'sheet',
    keywords: ['json to csv', 'convert json csv', 'export json', 'json csv converter'],
    type: 'static',
    addedAt: '2026-02-23',
    relatedTools: ['csv-to-json', 'json-formatter', 'sql-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/json-to-csv').then((mod) => ({ default: mod.JsonToCsv })),
  },
  'xml-formatter': {
    id: 'xml-formatter',
    title: 'XML Formatter',
    description: 'Format and beautify XML documents',
    longDescription:
      'Pretty-print XML with proper indentation and validate structure. Makes XML configs, SOAP responses, and RSS feeds readable for debugging.',
    category: 'developer',
    icon: 'code-xml',
    keywords: ['xml formatter', 'format xml', 'xml beautifier', 'pretty print xml'],
    type: 'static',
    addedAt: '2026-02-24',
    relatedTools: ['json-formatter', 'html-encoder', 'sql-formatter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/xml-formatter').then((mod) => ({ default: mod.XmlFormatter })),
  },
  'password-strength-checker': {
    id: 'password-strength-checker',
    title: 'Password Strength Checker',
    description: 'Check password strength and get improvement tips',
    longDescription:
      'Analyze password strength with a visual score meter and actionable feedback. Checks length, character diversity, and common patterns — all locally in your browser.',
    category: 'security',
    icon: 'shield-alert',
    keywords: ['password strength', 'password checker', 'strong password test', 'password meter'],
    type: 'static',
    addedAt: '2026-02-24',
    relatedTools: ['password-generator', 'hash-generator', 'jwt-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/password-strength-checker').then((mod) => ({
        default: mod.PasswordStrengthChecker,
      })),
  },
  'credit-card-validator': {
    id: 'credit-card-validator',
    title: 'Credit Card Validator',
    description: 'Validate card numbers with the Luhn algorithm',
    longDescription:
      'Check if a credit or debit card number is structurally valid using the Luhn checksum. Detects Visa, Mastercard, Amex, and Discover card types.',
    category: 'security',
    icon: 'credit-card',
    keywords: ['credit card validator', 'luhn check', 'card number validator', 'bin checker'],
    type: 'static',
    addedAt: '2026-02-25',
    relatedTools: ['password-strength-checker', 'hash-generator', 'random-string-generator'],
    faq: [
      {
        question: 'Does this verify if a card is active?',
        answer: 'No. This only checks the number format using the Luhn algorithm. It cannot verify balance, expiry, or whether the card is active.',
      },
      ...defaultFaq,
    ],
    component: () =>
      import('@/components/tools/credit-card-validator').then((mod) => ({
        default: mod.CreditCardValidator,
      })),
  },
  'binary-converter': {
    id: 'binary-converter',
    title: 'Binary Converter',
    description: 'Convert text to binary and binary back to text',
    longDescription:
      'Encode text strings to binary (base-2) representation or decode binary back to readable text. Useful for learning, debugging, and low-level data inspection.',
    category: 'encoding',
    icon: 'binary',
    keywords: ['binary converter', 'text to binary', 'binary to text', 'binary encoder'],
    type: 'static',
    addedAt: '2026-02-25',
    relatedTools: ['hex-encoder', 'base64-encoder', 'hash-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/binary-converter').then((mod) => ({ default: mod.BinaryConverter })),
  },
  'morse-code-translator': {
    id: 'morse-code-translator',
    title: 'Morse Code Translator',
    description: 'Translate text to Morse code and decode Morse to text',
    longDescription:
      'Convert between plain text and International Morse Code. Encode messages to dots and dashes or decode Morse code back to readable text.',
    category: 'encoding',
    icon: 'radio',
    keywords: ['morse code', 'morse translator', 'text to morse', 'morse decoder'],
    type: 'static',
    addedAt: '2026-02-26',
    relatedTools: ['binary-converter', 'rot13-encoder', 'base64-encoder'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/morse-code-translator').then((mod) => ({
        default: mod.MorseCodeTranslator,
      })),
  },
  'rot13-encoder': {
    id: 'rot13-encoder',
    title: 'ROT13 Encoder',
    description: 'Encode and decode text with ROT13 cipher',
    longDescription:
      'Apply ROT13 letter substitution cipher to any text. ROT13 is symmetric — encoding and decoding use the same operation. Often used for hiding spoilers.',
    category: 'encoding',
    icon: 'lock',
    keywords: ['rot13', 'rot13 encoder', 'caesar cipher', 'text cipher'],
    type: 'static',
    addedAt: '2026-02-26',
    relatedTools: ['base64-encoder', 'morse-code-translator', 'hash-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/rot13-encoder').then((mod) => ({ default: mod.Rot13Encoder })),
  },
  'duplicate-line-remover': {
    id: 'duplicate-line-remover',
    title: 'Duplicate Line Remover',
    description: 'Remove duplicate lines from text while preserving order',
    longDescription:
      'Clean up lists, logs, and data by removing duplicate lines. Optionally match case-sensitively and keep the first occurrence of each unique line.',
    category: 'text',
    icon: 'list-minus',
    keywords: ['remove duplicates', 'deduplicate lines', 'unique lines', 'duplicate remover'],
    type: 'static',
    addedAt: '2026-02-27',
    relatedTools: ['line-sorter', 'remove-line-breaks', 'word-counter'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/duplicate-line-remover').then((mod) => ({
        default: mod.DuplicateLineRemover,
      })),
  },
  'random-string-generator': {
    id: 'random-string-generator',
    title: 'Random String Generator',
    description: 'Generate random alphanumeric strings and tokens',
    longDescription:
      'Create cryptographically random strings for API keys, test data, and unique identifiers. Choose length, count, and character set including hex and symbols.',
    category: 'generators',
    icon: 'shuffle',
    keywords: ['random string', 'string generator', 'api key generator', 'random token'],
    type: 'static',
    addedAt: '2026-02-27',
    relatedTools: ['uuid-generator', 'password-generator', 'hash-generator'],
    faq: defaultFaq,
    component: () =>
      import('@/components/tools/random-string-generator').then((mod) => ({
        default: mod.RandomStringGenerator,
      })),
  },
  'jwt-generator': {
    id: 'jwt-generator',
    title: 'JWT Generator',
    description: 'Generate unsigned JWT token structure for testing',
    longDescription:
      'Build JSON Web Token header and payload structures for development and testing. Generates base64url-encoded unsigned tokens — pair with JWT Decoder for inspection.',
    category: 'developer',
    icon: 'key-round',
    keywords: ['jwt generator', 'create jwt', 'json web token generator', 'jwt builder'],
    type: 'static',
    addedAt: '2026-02-28',
    relatedTools: ['jwt-decoder', 'json-formatter', 'hash-generator'],
    faq: [
      {
        question: 'Is the generated JWT signed?',
        answer: 'No. This tool generates unsigned JWT structures for testing only. Production tokens must be signed with a secret key on the server.',
      },
      ...defaultFaq,
    ],
    component: () =>
      import('@/components/tools/jwt-generator').then((mod) => ({ default: mod.JwtGenerator })),
  },
  'qr-code-generator': {
    id: 'qr-code-generator',
    title: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs',
    longDescription: 'Create scannable QR codes for URLs, WiFi credentials, contact info, and plain text. Download as PNG instantly — all generated in your browser.',
    category: 'generators',
    icon: 'qr-code',
    keywords: ['qr code generator', 'create qr code', 'qr code maker', 'qr code online'],
    type: 'static',
    addedAt: '2026-03-01',
    relatedTools: ['url-encoder', 'uuid-generator', 'random-string-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/qr-code-generator').then((mod) => ({ default: mod.QrCodeGenerator })),
  },
  'unit-converter': {
    id: 'unit-converter',
    title: 'Unit Converter',
    description: 'Convert length, weight, and temperature units',
    longDescription: 'Convert between metric and imperial units for length, weight, and temperature. Supports meters, feet, kilograms, pounds, Celsius, Fahrenheit, and Kelvin.',
    category: 'math',
    icon: 'ruler',
    keywords: ['unit converter', 'length converter', 'weight converter', 'temperature converter'],
    type: 'static',
    addedAt: '2026-03-01',
    relatedTools: ['percentage-calculator', 'bmi-calculator', 'color-converter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/unit-converter').then((mod) => ({ default: mod.UnitConverter })),
  },
  'markdown-preview': {
    id: 'markdown-preview',
    title: 'Markdown Preview',
    description: 'Write Markdown with live HTML preview',
    longDescription: 'Real-time Markdown editor with side-by-side live preview. Supports headings, bold, italic, links, lists, and inline code.',
    category: 'text',
    icon: 'eye',
    keywords: ['markdown preview', 'markdown editor', 'live markdown', 'md preview'],
    type: 'static',
    addedAt: '2026-03-02',
    relatedTools: ['markdown-to-html', 'json-formatter', 'word-counter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/markdown-preview').then((mod) => ({ default: mod.MarkdownPreview })),
  },
  'http-status-codes': {
    id: 'http-status-codes',
    title: 'HTTP Status Codes',
    description: 'Lookup and search HTTP status codes',
    longDescription: 'Interactive reference for common HTTP status codes from 100 to 504. Search by code number or name — essential for API development and debugging.',
    category: 'network',
    icon: 'server',
    keywords: ['http status codes', 'status code list', '404 500', 'http response codes'],
    type: 'reference',
    addedAt: '2026-03-02',
    relatedTools: ['url-parser', 'json-formatter', 'jwt-decoder'],
    faq: defaultFaq,
    component: () => import('@/components/tools/http-status-codes').then((mod) => ({ default: mod.HttpStatusCodes })),
  },
  'cidr-calculator': {
    id: 'cidr-calculator',
    title: 'CIDR Calculator',
    description: 'Calculate subnet details from CIDR notation',
    longDescription: 'Parse CIDR notation to get network address, broadcast address, subnet mask, and usable host range. Essential for network planning and DevOps.',
    category: 'network',
    icon: 'network',
    keywords: ['cidr calculator', 'subnet calculator', 'ip subnet', 'network calculator'],
    type: 'static',
    addedAt: '2026-03-03',
    relatedTools: ['http-status-codes', 'url-parser', 'cron-parser'],
    faq: defaultFaq,
    component: () => import('@/components/tools/cidr-calculator').then((mod) => ({ default: mod.CidrCalculator })),
  },
  'roman-numeral-converter': {
    id: 'roman-numeral-converter',
    title: 'Roman Numeral Converter',
    description: 'Convert numbers to Roman numerals and back',
    longDescription: 'Convert Arabic numbers (1–3999) to Roman numerals and decode Roman numerals back to numbers. Useful for outlines, clocks, and historical dates.',
    category: 'math',
    icon: 'languages',
    keywords: ['roman numerals', 'roman numeral converter', 'number to roman', 'roman to number'],
    type: 'static',
    addedAt: '2026-03-03',
    relatedTools: ['number-to-words', 'percentage-calculator', 'unit-converter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/roman-numeral-converter').then((mod) => ({ default: mod.RomanNumeralConverter })),
  },
  'number-to-words': {
    id: 'number-to-words',
    title: 'Number to Words',
    description: 'Convert numbers to English words',
    longDescription: 'Transform numeric values into written English words. Supports numbers up to 999 million — useful for checks, invoices, and legal documents.',
    category: 'text',
    icon: 'letter-text',
    keywords: ['number to words', 'number in words', 'spell number', 'convert number to text'],
    type: 'static',
    addedAt: '2026-03-04',
    relatedTools: ['roman-numeral-converter', 'word-counter', 'case-converter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/number-to-words').then((mod) => ({ default: mod.NumberToWords })),
  },
  'reverse-text': {
    id: 'reverse-text',
    title: 'Reverse Text',
    description: 'Reverse characters, words, or lines in text',
    longDescription: 'Reverse text by character, word, or line. Useful for puzzles, string manipulation, and data transformation tasks.',
    category: 'text',
    icon: 'arrow-left-right',
    keywords: ['reverse text', 'flip text', 'backwards text', 'reverse string'],
    type: 'static',
    addedAt: '2026-03-04',
    relatedTools: ['case-converter', 'word-counter', 'palindrome-checker'],
    faq: defaultFaq,
    component: () => import('@/components/tools/reverse-text').then((mod) => ({ default: mod.ReverseText })),
  },
  'email-validator': {
    id: 'email-validator',
    title: 'Email Validator',
    description: 'Validate email address format',
    longDescription: 'Check if an email address has valid format including @ symbol, domain, and TLD. Runs locally — no email is sent or stored.',
    category: 'security',
    icon: 'mail-check',
    keywords: ['email validator', 'validate email', 'email format check', 'email regex'],
    type: 'static',
    addedAt: '2026-03-05',
    relatedTools: ['password-strength-checker', 'url-parser', 'hash-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/email-validator').then((mod) => ({ default: mod.EmailValidator })),
  },
  'url-parser': {
    id: 'url-parser',
    title: 'URL Parser',
    description: 'Break down URLs into components',
    longDescription: 'Parse any URL into protocol, hostname, port, path, query parameters, and hash fragment. Essential for debugging redirects and API endpoints.',
    category: 'developer',
    icon: 'link',
    keywords: ['url parser', 'parse url', 'url components', 'query string parser'],
    type: 'static',
    addedAt: '2026-03-05',
    relatedTools: ['url-encoder', 'url-decoder', 'http-status-codes'],
    faq: defaultFaq,
    component: () => import('@/components/tools/url-parser').then((mod) => ({ default: mod.UrlParser })),
  },
  'css-minifier': {
    id: 'css-minifier',
    title: 'CSS Minifier',
    description: 'Minify CSS by removing whitespace and comments',
    longDescription: 'Compress CSS files for production by stripping comments, whitespace, and unnecessary characters. Shows byte savings after minification.',
    category: 'developer',
    icon: 'minimize-2',
    keywords: ['css minifier', 'minify css', 'compress css', 'css optimizer'],
    type: 'static',
    addedAt: '2026-03-06',
    relatedTools: ['html-beautifier', 'json-formatter', 'xml-formatter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/css-minifier').then((mod) => ({ default: mod.CssMinifier })),
  },
  'html-beautifier': {
    id: 'html-beautifier',
    title: 'HTML Beautifier',
    description: 'Format and indent HTML code',
    longDescription: 'Pretty-print HTML with proper indentation for readability. Makes minified or messy HTML easy to read and debug.',
    category: 'developer',
    icon: 'code',
    keywords: ['html beautifier', 'format html', 'pretty print html', 'html formatter'],
    type: 'static',
    addedAt: '2026-03-06',
    relatedTools: ['html-encoder', 'css-minifier', 'markdown-to-html'],
    faq: defaultFaq,
    component: () => import('@/components/tools/html-beautifier').then((mod) => ({ default: mod.HtmlBeautifier })),
  },
  'yaml-to-json': {
    id: 'yaml-to-json',
    title: 'YAML to JSON',
    description: 'Convert YAML data to JSON format',
    longDescription: 'Parse YAML configuration files and convert to JSON. Useful for Kubernetes configs, Docker Compose, GitHub Actions, and CI pipelines.',
    category: 'developer',
    icon: 'arrow-right-left',
    keywords: ['yaml to json', 'convert yaml', 'yaml json converter', 'yaml parser'],
    type: 'static',
    addedAt: '2026-03-07',
    relatedTools: ['json-to-yaml', 'json-formatter', 'csv-to-json'],
    faq: defaultFaq,
    component: () => import('@/components/tools/yaml-to-json').then((mod) => ({ default: mod.YamlToJson })),
  },
  'json-to-yaml': {
    id: 'json-to-yaml',
    title: 'JSON to YAML',
    description: 'Convert JSON data to YAML format',
    longDescription: 'Transform JSON objects and arrays into clean YAML output. Ideal for creating config files, Kubernetes manifests, and Docker Compose files.',
    category: 'developer',
    icon: 'arrow-left-right',
    keywords: ['json to yaml', 'convert json yaml', 'json yaml converter'],
    type: 'static',
    addedAt: '2026-03-07',
    relatedTools: ['yaml-to-json', 'json-formatter', 'csv-to-json'],
    faq: defaultFaq,
    component: () => import('@/components/tools/json-to-yaml').then((mod) => ({ default: mod.JsonToYaml })),
  },
  'character-frequency-counter': {
    id: 'character-frequency-counter',
    title: 'Character Frequency Counter',
    description: 'Count how often each character appears in text',
    longDescription: 'Analyze character frequency distribution in any text. Shows count and percentage for each unique character — useful for cryptography and text analysis.',
    category: 'text',
    icon: 'bar-chart-3',
    keywords: ['character frequency', 'letter frequency', 'char count', 'frequency analysis'],
    type: 'static',
    addedAt: '2026-03-08',
    relatedTools: ['word-counter', 'hash-generator', 'reverse-text'],
    faq: defaultFaq,
    component: () => import('@/components/tools/character-frequency-counter').then((mod) => ({ default: mod.CharacterFrequencyCounter })),
  },
  'text-repeater': {
    id: 'text-repeater',
    title: 'Text Repeater',
    description: 'Repeat text multiple times with custom separators',
    longDescription: 'Generate repeated text strings with configurable count and separator. Useful for test data, patterns, and bulk text generation.',
    category: 'text',
    icon: 'repeat',
    keywords: ['text repeater', 'repeat text', 'duplicate text', 'string repeater'],
    type: 'static',
    addedAt: '2026-03-08',
    relatedTools: ['lorem-ipsum-generator', 'find-and-replace', 'word-counter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/text-repeater').then((mod) => ({ default: mod.TextRepeater })),
  },
  'find-and-replace': {
    id: 'find-and-replace',
    title: 'Find and Replace',
    description: 'Find and replace text with optional regex support',
    longDescription: 'Bulk find and replace in text with case sensitivity and regex options. Shows replacement count and supports complex pattern matching.',
    category: 'text',
    icon: 'replace',
    keywords: ['find and replace', 'search replace', 'text replace', 'bulk replace'],
    type: 'static',
    addedAt: '2026-03-09',
    relatedTools: ['regex-tester', 'case-converter', 'remove-line-breaks'],
    faq: defaultFaq,
    component: () => import('@/components/tools/find-and-replace').then((mod) => ({ default: mod.FindAndReplace })),
  },
  'palindrome-checker': {
    id: 'palindrome-checker',
    title: 'Palindrome Checker',
    description: 'Check if text reads the same forwards and backwards',
    longDescription: 'Detect palindromes in words, phrases, and sentences. Optionally ignore case and spaces for flexible matching.',
    category: 'text',
    icon: 'flip-horizontal',
    keywords: ['palindrome checker', 'is palindrome', 'palindrome test', 'reverse word'],
    type: 'static',
    addedAt: '2026-03-09',
    relatedTools: ['reverse-text', 'word-counter', 'case-converter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/palindrome-checker').then((mod) => ({ default: mod.PalindromeChecker })),
  },
  'discount-calculator': {
    id: 'discount-calculator',
    title: 'Discount Calculator',
    description: 'Calculate sale price and savings from a discount percentage',
    longDescription: 'Find the final price after applying a percentage discount. See exactly how much you save on sales, coupons, and promotional offers.',
    category: 'calculators',
    icon: 'badge-percent',
    keywords: ['discount calculator', 'sale price', 'percent off', 'coupon calculator'],
    type: 'static',
    addedAt: '2026-03-10',
    relatedTools: ['tip-calculator', 'gst-calculator', 'percentage-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/discount-calculator').then((mod) => ({ default: mod.DiscountCalculator })),
  },
  'simple-interest-calculator': {
    id: 'simple-interest-calculator',
    title: 'Simple Interest Calculator',
    description: 'Calculate simple interest on loans and deposits',
    longDescription: 'Compute simple interest using principal, annual rate, and time period. Shows total interest earned or owed and final amount.',
    category: 'calculators',
    icon: 'trending-up',
    keywords: ['simple interest', 'interest calculator', 'loan interest', 'SI calculator'],
    type: 'static',
    addedAt: '2026-03-10',
    relatedTools: ['compound-interest-calculator', 'emi-calculator', 'sip-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/simple-interest-calculator').then((mod) => ({ default: mod.SimpleInterestCalculator })),
  },
  'fraction-calculator': {
    id: 'fraction-calculator',
    title: 'Fraction Calculator',
    description: 'Add, subtract, multiply, and divide fractions',
    longDescription: 'Perform arithmetic on fractions and get simplified results. Supports proper fractions, improper fractions, and whole numbers.',
    category: 'math',
    icon: 'divide',
    keywords: ['fraction calculator', 'add fractions', 'simplify fraction', 'math fractions'],
    type: 'static',
    addedAt: '2026-03-11',
    relatedTools: ['percentage-calculator', 'binary-converter', 'roman-numeral-converter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/fraction-calculator').then((mod) => ({ default: mod.FractionCalculator })),
  },
  'reading-time-calculator': {
    id: 'reading-time-calculator',
    title: 'Reading Time Calculator',
    description: 'Estimate how long it takes to read your text',
    longDescription: 'Calculate reading time for articles, blog posts, and documents based on average reading speed of 200 words per minute.',
    category: 'text',
    icon: 'book-open',
    keywords: ['reading time', 'read time calculator', 'blog reading time', 'words per minute'],
    type: 'static',
    addedAt: '2026-03-11',
    relatedTools: ['word-counter', 'word-frequency-counter', 'slug-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/reading-time-calculator').then((mod) => ({ default: mod.ReadingTimeCalculator })),
  },
  'word-frequency-counter': {
    id: 'word-frequency-counter',
    title: 'Word Frequency Counter',
    description: 'Count how often each word appears in text',
    longDescription: 'Analyze word frequency distribution with counts and percentages. Useful for SEO keyword analysis, writing, and text mining.',
    category: 'text',
    icon: 'bar-chart-2',
    keywords: ['word frequency', 'word count analysis', 'keyword frequency', 'text analysis'],
    type: 'static',
    addedAt: '2026-03-12',
    relatedTools: ['word-counter', 'character-frequency-counter', 'reading-time-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/word-frequency-counter').then((mod) => ({ default: mod.WordFrequencyCounter })),
  },
  'list-randomizer': {
    id: 'list-randomizer',
    title: 'List Randomizer',
    description: 'Randomly shuffle a list of items',
    longDescription: 'Shuffle lines or list items in random order using Fisher-Yates algorithm. Perfect for raffles, random selection, and test data.',
    category: 'text',
    icon: 'shuffle',
    keywords: ['list randomizer', 'shuffle list', 'random order', 'randomize names'],
    type: 'static',
    addedAt: '2026-03-12',
    relatedTools: ['random-number-generator', 'line-sorter', 'duplicate-line-remover'],
    faq: defaultFaq,
    component: () => import('@/components/tools/list-randomizer').then((mod) => ({ default: mod.ListRandomizer })),
  },
  'whitespace-normalizer': {
    id: 'whitespace-normalizer',
    title: 'Whitespace Normalizer',
    description: 'Clean up extra spaces, tabs, and blank lines',
    longDescription: 'Normalize messy text by collapsing multiple spaces, trimming lines, and removing excessive blank lines. Cleans copy-pasted content fast.',
    category: 'text',
    icon: 'space',
    keywords: ['whitespace normalizer', 'remove extra spaces', 'clean text', 'trim whitespace'],
    type: 'static',
    addedAt: '2026-03-13',
    relatedTools: ['remove-line-breaks', 'find-and-replace', 'strip-html-tags'],
    faq: defaultFaq,
    component: () => import('@/components/tools/whitespace-normalizer').then((mod) => ({ default: mod.WhitespaceNormalizer })),
  },
  'javascript-minifier': {
    id: 'javascript-minifier',
    title: 'JavaScript Minifier',
    description: 'Minify JavaScript by removing comments and whitespace',
    longDescription: 'Compress JavaScript files for production by stripping comments and unnecessary whitespace. Shows byte savings after minification.',
    category: 'developer',
    icon: 'file-code',
    keywords: ['javascript minifier', 'minify js', 'compress javascript', 'js optimizer'],
    type: 'static',
    addedAt: '2026-03-13',
    relatedTools: ['css-minifier', 'json-formatter', 'html-beautifier'],
    faq: defaultFaq,
    component: () => import('@/components/tools/javascript-minifier').then((mod) => ({ default: mod.JavascriptMinifier })),
  },
  'html-to-markdown': {
    id: 'html-to-markdown',
    title: 'HTML to Markdown',
    description: 'Convert HTML markup to Markdown format',
    longDescription: 'Transform HTML into clean Markdown syntax. Useful for migrating content, documentation workflows, and CMS exports.',
    category: 'developer',
    icon: 'file-text',
    keywords: ['html to markdown', 'convert html markdown', 'html markdown converter'],
    type: 'static',
    addedAt: '2026-03-14',
    relatedTools: ['markdown-to-html', 'markdown-preview', 'strip-html-tags'],
    faq: defaultFaq,
    component: () => import('@/components/tools/html-to-markdown').then((mod) => ({ default: mod.HtmlToMarkdown })),
  },
  'ip-converter': {
    id: 'ip-converter',
    title: 'IP Address Converter',
    description: 'Convert IPv4 addresses to decimal and hex',
    longDescription: 'Convert between IPv4 dotted notation, decimal (long integer), and hexadecimal formats. Essential for network debugging and database storage.',
    category: 'network',
    icon: 'globe',
    keywords: ['ip converter', 'ipv4 to decimal', 'ip to long', 'ip address converter'],
    type: 'static',
    addedAt: '2026-03-14',
    relatedTools: ['cidr-calculator', 'url-parser', 'http-status-codes'],
    faq: defaultFaq,
    component: () => import('@/components/tools/ip-converter').then((mod) => ({ default: mod.IpConverter })),
  },
  'mac-address-generator': {
    id: 'mac-address-generator',
    title: 'MAC Address Generator',
    description: 'Generate random MAC addresses for testing',
    longDescription: 'Create random locally administered MAC addresses with colon, dash, or no separator. Ideal for virtualization, networking labs, and test environments.',
    category: 'network',
    icon: 'cable',
    keywords: ['mac address generator', 'random mac', 'fake mac address', 'network testing'],
    type: 'static',
    addedAt: '2026-03-15',
    relatedTools: ['ip-converter', 'cidr-calculator', 'uuid-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/mac-address-generator').then((mod) => ({ default: mod.MacAddressGenerator })),
  },
  'hmac-generator': {
    id: 'hmac-generator',
    title: 'HMAC Generator',
    description: 'Generate HMAC signatures with SHA-256, SHA-384, or SHA-512',
    longDescription: 'Compute HMAC (Hash-based Message Authentication Code) using a secret key and message. Used for API authentication, JWT signing, and webhook verification.',
    category: 'security',
    icon: 'key-round',
    keywords: ['hmac generator', 'hmac sha256', 'message authentication', 'api signature'],
    type: 'static',
    addedAt: '2026-03-15',
    relatedTools: ['hash-generator', 'jwt-generator', 'jwt-decoder'],
    faq: defaultFaq,
    component: () => import('@/components/tools/hmac-generator').then((mod) => ({ default: mod.HmacGenerator })),
  },
  'chmod-calculator': {
    id: 'chmod-calculator',
    title: 'Chmod Calculator',
    description: 'Convert between octal and symbolic file permissions',
    longDescription: 'Translate Unix file permissions between octal (755) and symbolic (rwxr-xr-x) notation. See owner, group, and others breakdown instantly.',
    category: 'developer',
    icon: 'terminal',
    keywords: ['chmod calculator', 'file permissions', 'octal to symbolic', 'unix permissions'],
    type: 'static',
    addedAt: '2026-03-16',
    relatedTools: ['binary-converter', 'hex-encoder', 'hash-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/chmod-calculator').then((mod) => ({ default: mod.ChmodCalculator })),
  },
  'aspect-ratio-calculator': {
    id: 'aspect-ratio-calculator',
    title: 'Aspect Ratio Calculator',
    description: 'Calculate width or height from aspect ratio',
    longDescription: 'Compute missing dimensions for 16:9, 4:3, 1:1, and custom aspect ratios. Essential for responsive design, video, and image sizing.',
    category: 'developer',
    icon: 'ratio',
    keywords: ['aspect ratio calculator', '16:9 calculator', 'image dimensions', 'responsive design'],
    type: 'static',
    addedAt: '2026-03-16',
    relatedTools: ['color-converter', 'unit-converter', 'qr-code-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/aspect-ratio-calculator').then((mod) => ({ default: mod.AspectRatioCalculator })),
  },
  'vat-calculator': {
    id: 'vat-calculator',
    title: 'VAT Calculator',
    description: 'Calculate VAT inclusive and exclusive amounts',
    longDescription: 'Compute Value Added Tax for EU and international invoices. Supports common VAT rates with exclusive and inclusive calculation modes.',
    category: 'calculators',
    icon: 'receipt',
    keywords: ['vat calculator', 'value added tax', 'vat inclusive', 'vat exclusive'],
    type: 'static',
    addedAt: '2026-03-17',
    relatedTools: ['gst-calculator', 'discount-calculator', 'tip-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/vat-calculator').then((mod) => ({ default: mod.VatCalculator })),
  },
  'salary-calculator': {
    id: 'salary-calculator',
    title: 'Salary Calculator',
    description: 'Convert between hourly rate and annual salary',
    longDescription: 'Calculate annual, monthly, and hourly pay from any starting point. Adjust hours per week for full-time, part-time, or contract work.',
    category: 'calculators',
    icon: 'banknote',
    keywords: ['salary calculator', 'hourly to annual', 'annual to hourly', 'wage calculator'],
    type: 'static',
    addedAt: '2026-03-17',
    relatedTools: ['tip-calculator', 'emi-calculator', 'sip-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/salary-calculator').then((mod) => ({ default: mod.SalaryCalculator })),
  },
  'ratio-calculator': {
    id: 'ratio-calculator',
    title: 'Ratio Calculator',
    description: 'Solve proportions and find missing values',
    longDescription: 'Calculate missing values in proportions (a:b = c:x). Useful for recipes, scaling, maps, and any ratio-based math problem.',
    category: 'math',
    icon: 'scale',
    keywords: ['ratio calculator', 'proportion calculator', 'solve proportion', 'cross multiply'],
    type: 'static',
    addedAt: '2026-03-18',
    relatedTools: ['fraction-calculator', 'percentage-calculator', 'unit-converter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/ratio-calculator').then((mod) => ({ default: mod.RatioCalculator })),
  },
  'scientific-notation-converter': {
    id: 'scientific-notation-converter',
    title: 'Scientific Notation Converter',
    description: 'Convert numbers to and from scientific notation',
    longDescription: 'Transform large and small numbers into scientific notation and back. Useful for science, engineering, and programming applications.',
    category: 'math',
    icon: 'superscript',
    keywords: ['scientific notation', 'e notation', 'convert scientific notation', 'standard form'],
    type: 'static',
    addedAt: '2026-03-18',
    relatedTools: ['binary-converter', 'fraction-calculator', 'percentage-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/scientific-notation-converter').then((mod) => ({ default: mod.ScientificNotationConverter })),
  },
  'sentence-counter': {
    id: 'sentence-counter',
    title: 'Sentence Counter',
    description: 'Count sentences and average words per sentence',
    longDescription: 'Analyze text structure by counting sentences, words, and average sentence length. Helpful for writing clarity and readability checks.',
    category: 'text',
    icon: 'text-quote',
    keywords: ['sentence counter', 'count sentences', 'words per sentence', 'text analysis'],
    type: 'static',
    addedAt: '2026-03-19',
    relatedTools: ['word-counter', 'paragraph-counter', 'reading-time-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/sentence-counter').then((mod) => ({ default: mod.SentenceCounter })),
  },
  'paragraph-counter': {
    id: 'paragraph-counter',
    title: 'Paragraph Counter',
    description: 'Count paragraphs, words, and characters in text',
    longDescription: 'Count paragraphs separated by blank lines along with total words and characters. Useful for essays, articles, and content editing.',
    category: 'text',
    icon: 'align-left',
    keywords: ['paragraph counter', 'count paragraphs', 'text structure', 'writing analysis'],
    type: 'static',
    addedAt: '2026-03-19',
    relatedTools: ['sentence-counter', 'word-counter', 'reading-time-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/paragraph-counter').then((mod) => ({ default: mod.ParagraphCounter })),
  },
  'ascii-converter': {
    id: 'ascii-converter',
    title: 'ASCII Converter',
    description: 'Convert characters to ASCII codes and back',
    longDescription: 'Look up ASCII/Unicode code points for any character, or convert decimal and hex codes back to characters. Essential for encoding debugging.',
    category: 'encoding',
    icon: 'hash',
    keywords: ['ascii converter', 'char to ascii', 'ascii code', 'character code'],
    type: 'static',
    addedAt: '2026-03-20',
    relatedTools: ['hex-encoder', 'binary-converter', 'html-encoder'],
    faq: defaultFaq,
    component: () => import('@/components/tools/ascii-converter').then((mod) => ({ default: mod.AsciiConverter })),
  },
  'csv-formatter': {
    id: 'csv-formatter',
    title: 'CSV Formatter',
    description: 'Format and align CSV data for readability',
    longDescription: 'Parse CSV data and display it in aligned columns for easy reading and debugging. Handles quoted fields and commas correctly.',
    category: 'developer',
    icon: 'table',
    keywords: ['csv formatter', 'format csv', 'align csv', 'csv viewer'],
    type: 'static',
    addedAt: '2026-03-20',
    relatedTools: ['csv-to-json', 'json-to-csv', 'json-formatter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/csv-formatter').then((mod) => ({ default: mod.CsvFormatter })),
  },
  'json-string-escaper': {
    id: 'json-string-escaper',
    title: 'JSON String Escaper',
    description: 'Escape and unescape strings for JSON',
    longDescription: 'Escape special characters in strings for safe JSON embedding, or unescape JSON string values back to plain text.',
    category: 'developer',
    icon: 'quote',
    keywords: ['json escape', 'escape string json', 'json unescape', 'string escaper'],
    type: 'static',
    addedAt: '2026-03-21',
    relatedTools: ['json-formatter', 'html-encoder', 'url-encoder'],
    faq: defaultFaq,
    component: () => import('@/components/tools/json-string-escaper').then((mod) => ({ default: mod.JsonStringEscaper })),
  },
  'user-agent-parser': {
    id: 'user-agent-parser',
    title: 'User-Agent Parser',
    description: 'Parse browser, OS, and device from User-Agent strings',
    longDescription: 'Extract browser name, operating system, and device type from HTTP User-Agent headers. Useful for web debugging and analytics.',
    category: 'developer',
    icon: 'monitor-smartphone',
    keywords: ['user agent parser', 'parse user agent', 'browser detection', 'ua string'],
    type: 'static',
    addedAt: '2026-03-21',
    relatedTools: ['url-parser', 'http-status-codes', 'email-validator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/user-agent-parser').then((mod) => ({ default: mod.UserAgentParser })),
  },
  'tab-to-spaces': {
    id: 'tab-to-spaces',
    title: 'Tab to Spaces',
    description: 'Convert tabs to spaces in code and text',
    longDescription: 'Replace tab characters with configurable spaces (2–8). Standardize indentation in code pasted from different editors.',
    category: 'developer',
    icon: 'indent-increase',
    keywords: ['tab to spaces', 'convert tabs', 'indentation converter', 'spaces tabs'],
    type: 'static',
    addedAt: '2026-03-22',
    relatedTools: ['line-sorter', 'whitespace-normalizer', 'json-formatter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/tab-to-spaces').then((mod) => ({ default: mod.TabToSpaces })),
  },
  'cron-generator': {
    id: 'cron-generator',
    title: 'Cron Expression Generator',
    description: 'Build cron schedules with presets and custom fields',
    longDescription: 'Generate cron expressions visually with presets for common schedules or custom minute, hour, day, month, and weekday fields.',
    category: 'developer',
    icon: 'calendar-clock',
    keywords: ['cron generator', 'create cron expression', 'cron builder', 'schedule generator'],
    type: 'static',
    addedAt: '2026-03-22',
    relatedTools: ['cron-parser', 'timezone-converter', 'unix-timestamp-converter'],
    faq: defaultFaq,
    component: () => import('@/components/tools/cron-generator').then((mod) => ({ default: mod.CronGenerator })),
  },
  'levenshtein-calculator': {
    id: 'levenshtein-calculator',
    title: 'Levenshtein Distance Calculator',
    description: 'Measure string similarity with edit distance',
    longDescription: 'Calculate the Levenshtein edit distance between two strings and show similarity percentage. Used in spell checkers, fuzzy search, and DNA analysis.',
    category: 'text',
    icon: 'git-compare',
    keywords: ['levenshtein distance', 'edit distance', 'string similarity', 'fuzzy match'],
    type: 'static',
    addedAt: '2026-03-23',
    relatedTools: ['text-diff', 'palindrome-checker', 'find-and-replace'],
    faq: defaultFaq,
    component: () => import('@/components/tools/levenshtein-calculator').then((mod) => ({ default: mod.LevenshteinCalculator })),
  },
  'markdown-table-generator': {
    id: 'markdown-table-generator',
    title: 'Markdown Table Generator',
    description: 'Create Markdown tables from CSV or tab-separated data',
    longDescription: 'Convert comma, tab, or pipe-separated data into formatted Markdown tables. Perfect for README files, documentation, and GitHub wikis.',
    category: 'developer',
    icon: 'table-2',
    keywords: ['markdown table generator', 'csv to markdown table', 'create markdown table'],
    type: 'static',
    addedAt: '2026-03-24',
    relatedTools: ['markdown-to-html', 'markdown-preview', 'csv-to-json'],
    faq: defaultFaq,
    component: () => import('@/components/tools/markdown-table-generator').then((mod) => ({ default: mod.MarkdownTableGenerator })),
  },
  'uuid-validator': {
    id: 'uuid-validator',
    title: 'UUID Validator',
    description: 'Validate UUID format and identify version',
    longDescription: 'Check if a string is a valid RFC 4122 UUID and identify its version (v1–v8) and variant. Useful for API debugging and data validation.',
    category: 'developer',
    icon: 'badge-check',
    keywords: ['uuid validator', 'validate uuid', 'uuid version', 'check uuid'],
    type: 'static',
    addedAt: '2026-03-24',
    relatedTools: ['uuid-generator', 'jwt-decoder', 'hash-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/uuid-validator').then((mod) => ({ default: mod.UuidValidator })),
  },
  'margin-calculator': {
    id: 'margin-calculator',
    title: 'Profit Margin Calculator',
    description: 'Calculate profit margin and markup from cost and price',
    longDescription: 'Compute profit, profit margin percentage, and markup percentage from cost price and selling price. Essential for pricing and retail decisions.',
    category: 'calculators',
    icon: 'chart-line',
    keywords: ['profit margin calculator', 'markup calculator', 'margin vs markup', 'pricing calculator'],
    type: 'static',
    addedAt: '2026-03-25',
    relatedTools: ['discount-calculator', 'gst-calculator', 'vat-calculator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/margin-calculator').then((mod) => ({ default: mod.MarginCalculator })),
  },
  'css-gradient-generator': {
    id: 'css-gradient-generator',
    title: 'CSS Gradient Generator',
    description: 'Create linear CSS gradients with live preview',
    longDescription: 'Build linear CSS gradients visually with color pickers and angle control. Copy production-ready background CSS instantly.',
    category: 'developer',
    icon: 'paintbrush',
    keywords: ['css gradient generator', 'linear gradient css', 'gradient maker', 'background gradient'],
    type: 'static',
    addedAt: '2026-03-25',
    relatedTools: ['color-converter', 'css-minifier', 'random-color-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/css-gradient-generator').then((mod) => ({ default: mod.CssGradientGenerator })),
  },
  'meta-tag-generator': {
    id: 'meta-tag-generator',
    title: 'Meta Tag Generator',
    description: 'Generate SEO and Open Graph meta tags',
    longDescription: 'Create HTML meta tags for SEO, Open Graph, and Twitter Cards. Copy ready-to-paste tags for your website head section.',
    category: 'developer',
    icon: 'tags',
    keywords: ['meta tag generator', 'og tags', 'seo meta tags', 'open graph generator'],
    type: 'static',
    addedAt: '2026-03-26',
    relatedTools: ['slug-generator', 'markdown-preview', 'html-beautifier'],
    faq: defaultFaq,
    component: () => import('@/components/tools/meta-tag-generator').then((mod) => ({ default: mod.MetaTagGenerator })),
  },
  'add-line-numbers': {
    id: 'add-line-numbers',
    title: 'Add Line Numbers',
    description: 'Add line numbers to text and code',
    longDescription: 'Number every line in text or code with configurable starting number. Useful for references, documentation, and code snippets.',
    category: 'text',
    icon: 'list-ordered',
    keywords: ['add line numbers', 'number lines', 'line numbering', 'code line numbers'],
    type: 'static',
    addedAt: '2026-03-26',
    relatedTools: ['line-sorter', 'text-diff', 'remove-line-breaks'],
    faq: defaultFaq,
    component: () => import('@/components/tools/add-line-numbers').then((mod) => ({ default: mod.AddLineNumbers })),
  },
  'extract-urls': {
    id: 'extract-urls',
    title: 'Extract URLs',
    description: 'Extract all URLs from text',
    longDescription: 'Find and extract every unique HTTP and HTTPS URL from any block of text. Useful for link auditing, scraping prep, and content analysis.',
    category: 'text',
    icon: 'link-2',
    keywords: ['extract urls', 'find urls in text', 'url extractor', 'parse links'],
    type: 'static',
    addedAt: '2026-03-27',
    relatedTools: ['url-parser', 'extract-emails', 'strip-html-tags'],
    faq: defaultFaq,
    component: () => import('@/components/tools/extract-urls').then((mod) => ({ default: mod.ExtractUrls })),
  },
  'extract-emails': {
    id: 'extract-emails',
    title: 'Extract Emails',
    description: 'Extract all email addresses from text',
    longDescription: 'Find and extract every unique email address from any block of text. Useful for contact list building, data cleaning, and content analysis.',
    category: 'text',
    icon: 'mail',
    keywords: ['extract emails', 'find emails in text', 'email extractor', 'parse emails'],
    type: 'static',
    addedAt: '2026-03-27',
    relatedTools: ['email-validator', 'extract-urls', 'find-and-replace'],
    faq: defaultFaq,
    component: () => import('@/components/tools/extract-emails').then((mod) => ({ default: mod.ExtractEmails })),
  },
  'random-color-generator': {
    id: 'random-color-generator',
    title: 'Random Color Generator',
    description: 'Generate random colors with HEX, RGB, and HSL values',
    longDescription: 'Generate random colors for design mockups, testing, and inspiration. Shows HEX, RGB, and HSL values with one-click copy.',
    category: 'generators',
    icon: 'palette',
    keywords: ['random color generator', 'random hex color', 'color picker random', 'generate color'],
    type: 'static',
    addedAt: '2026-03-28',
    relatedTools: ['color-converter', 'css-gradient-generator', 'qr-code-generator'],
    faq: defaultFaq,
    component: () => import('@/components/tools/random-color-generator').then((mod) => ({ default: mod.RandomColorGenerator })),
  },
  'naming-convention-converter': {
    id: 'naming-convention-converter',
    title: 'Naming Convention Converter',
    description: 'Convert between camelCase, snake_case, kebab-case, and more',
    longDescription: 'Transform identifiers between camelCase, PascalCase, snake_case, SCREAMING_SNAKE, kebab-case, and dot.case. Essential for refactoring code.',
    category: 'developer',
    icon: 'case-sensitive',
    keywords: ['naming convention', 'camelCase to snake_case', 'kebab case converter', 'variable naming'],
    type: 'static',
    addedAt: '2026-03-28',
    relatedTools: ['case-converter', 'slug-generator', 'find-and-replace'],
    faq: defaultFaq,
    component: () => import('@/components/tools/naming-convention-converter').then((mod) => ({ default: mod.NamingConventionConverter })),
  },
}

export function getAllTools(): ToolDefinition[] {
  return Object.values(tools)
}

export function getToolCount(): number {
  return getAllTools().length
}

export function getCategoryById(categoryId: string): CategoryDefinition | undefined {
  return categories.find((category) => category.id === categoryId)
}

export function getCategoryName(categoryId: string): string {
  return getCategoryById(categoryId)?.name ?? categoryId
}

export function getToolsByCategory(categoryId: string): ToolDefinition[] {
  return getAllTools().filter((tool) => tool.category === categoryId)
}

export function searchTools(query: string): ToolDefinition[] {
  const lowerQuery = query.toLowerCase().trim()
  if (!lowerQuery) return []

  return getAllTools().filter((tool) => {
    const categoryName = getCategoryName(tool.category).toLowerCase()
    return (
      tool.title.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      categoryName.includes(lowerQuery) ||
      tool.keywords.some((keyword) => keyword.toLowerCase().includes(lowerQuery))
    )
  })
}

export function getTrendingTools(): ToolDefinition[] {
  return [
    'meta-tag-generator',
    'css-gradient-generator',
    'naming-convention-converter',
    'margin-calculator',
    'random-color-generator',
    'uuid-validator',
  ]
    .map((id) => tools[id])
    .filter(Boolean)
}

export function getRecentlyAddedTools(limit = 4): ToolDefinition[] {
  return getAllTools()
    .sort((a, b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime())
    .slice(0, limit)
}

export function getRelatedTools(tool: ToolDefinition): ToolDefinition[] {
  return (tool.relatedTools ?? [])
    .map((id) => tools[id])
    .filter(Boolean)
    .slice(0, 4)
}

export function getToolIds(): string[] {
  return Object.keys(tools)
}
